version: '3'
services:
  php-fpm:
    container_name: process-repository-php-fpm
    build:
      context: ./docker/php
      dockerfile: php-fpm.dockerfile
    working_dir: /var/www
    external_links:
     - web.db
    volumes:
      - ./:/var/www
  nginx:
    container_name: process-repository-nginx
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
    links:
      - php-fpm
    external_links:
     - web.nginx-proxy
    environment:
     - VIRTUAL_HOST=laravel.com
     - VIRTUAL_PORT=9000
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    expose:
      - "80"
    depends_on:
      - php-fpm
    restart: always

networks:
  default:
    external:
      name: main